[COF-110] Review API 문서화
jeyook/coffeeeeeeee-backend pull request #73
Opened 2024-02-20 16:33 UTC by JeYeongR

## Objectives
> 이 PR의 목적은 무엇인가요?

Review API 문서화를 위해 스웨거를 작성했습니다.

<br>

## Key Results
> 이 PR의 결과물은 어떤것인가요?   
<br>

<img width="1417" alt="image" src="https://github.com/jeyook/coffeeeeeeee-backend/assets/113500815/e3ddf2a3-cd22-4f10-9494-5a128ac01cfd">

<br>

## Review Points
> 리뷰 할 때 특별히 이런 부분을 봐주세요.   
<br>

2024-02-21 09:35 UTC, JISUlicious requested changes

2024-02-21 09:35 UTC, JISUlicious commented on src/review/decorator/review-api-documentation.ts
> +}
상세하게 작성되었는게 막상 API 문서에는 표시가 안되는게 아숩네요

2024-02-21 09:35 UTC, JISUlicious commented on src/review/decorator/review-api-documentation.ts
> +    maxLength: 500,
maxLength는 constraint으로 지정된 중요한 사항이니 api 문서에 표시되도록 방법을 찾으면 좋겠습니다~

혹시 제가 못찾고 있는거라면 알려주세요~

2024-02-21 09:36 UTC, JISUlicious commented
전체적으로 꼼꼼하게 작성되어서 좋네요! 코멘트들 확인 한번 부탁드릴게요

2024-02-21 18:15 UTC, JeYeongR commented on src/review/decorator/review-api-documentation.ts
> +    maxLength: 500,
수정했습니다..! maxLength가 form-data에서는 표시가 안되네요

2024-02-22 13:29 UTC, JISUlicious approved these changes

2024-02-22 15:11 UTC, merged