[COF-088] bookmark test 추가
jeyook/coffeeeeeeee-backend pull request #80
Opened 2024-03-07 07:59 UTC by Wanderer94

## Objectives
> 이 PR의 목적은 무엇인가요?
추가된 예외 처리 사항에 대해서 테스트코드를 진행했습니다.

<br>

## Key Results
> 이 PR의 결과물은 어떤것인가요?   
<br>
![image](https://github.com/jeyook/coffeeeeeeee-backend/assets/60542972/93a5315b-5db1-4e4c-8b23-427ed65463b0)

<br>

## Review Points
> 리뷰 할 때 특별히 이런 부분을 봐주세요.   
<br>
remove, softremove, delete의 차이점에 대해서 학습중에 있습니다
성공적으로 삭제되었을 때 어떻게 알려줘야 할 지 의문입니다.

2024-03-13 11:38 UTC, JeYeongR requested changes
고생하셨습니다~

2024-03-13 11:38 UTC, JeYeongR commented on src/bookmark/bookmark.service.spec.ts
> +    });
이 부분 확인해보니 페이지 넘어갔을때 나오는 예외인거 같아요! 확인 부탁드립니다.

2024-03-13 11:38 UTC, JeYeongR commented on src/bookmark/bookmark.service.spec.ts
> +      spyDeleteBookmarkFn.mockResolvedValueOnce(Promise.resolve({ affected: 1 }));
저는 보통 삭제같은 경우는 리턴을 목처리 안 해요!

2024-03-13 11:38 UTC, JeYeongR commented on src/bookmark/bookmark.service.ts
> +    await this.bookmarkRepository.delete(foundBookmark);
저는 delete랑 remove 차이는 엔티티를 넣어주냐, 조건을 넣어주냐 차이로 이해했어요.
soft는 논리적 삭제로 실제로 db에는 남아있는데, deleteAt이 채워지면서 삭제된걸로 인식됩니다!
Typeorm은 자체적으로 논리적 삭제를 지원해줘요!!

참고: 
https://velog.io/@phw3071/TypeOrm-remove-%EC%99%80-delete-%EC%9D%98-%EC%B0%A8%EC%9D%B4

https://lahezy.tistory.com/96

2024-03-14 08:12 UTC, JeYeongR commented on src/bookmark/bookmark.service.ts
> +    await this.bookmarkRepository.delete(foundBookmark);
추가적으로 TypeORM에서는 논리적 삭제를 지원하기 때문에 repository api로 조회할때 deleteAt이 채워져있는 애들은 빼고 조회합니다!!

2024-03-14 08:18 UTC, JeYeongR commented on src/bookmark/bookmark.service.ts
> +    await this.bookmarkRepository.delete(foundBookmark);
더 찾아보니 이 부분도 다르데요! 
https://velog.io/@fj2008/TypeORM-remove-vs-delete-%EC%B0%A8%EC%9D%B4%EC%A0%90

2024-03-14 14:49 UTC, Wanderer94 commented on src/bookmark/bookmark.service.ts
> +    await this.bookmarkRepository.delete(foundBookmark);
저도 마지막 댓 보고 고민했었어요 북마크의 경우에는 delete로 삭제해 주는게 좋을 것 같다는 생각이 들었습니다 그래야 안정성이 높아 질 것 같고 굳이 리소스를 낭비할 필요가 없다고 느껴져서요 바로 반영하겠습니다!

2024-03-14 14:50 UTC, Wanderer94 commented on src/bookmark/bookmark.service.spec.ts
> +      spyDeleteBookmarkFn.mockResolvedValueOnce(Promise.resolve({ affected: 1 }));
아 248번 라인을 이렇게 바꿔야할까요
`jest.spyOn(mockBookmarkRepository, 'delete');`

2024-03-14 14:51 UTC, Wanderer94 commented on src/bookmark/bookmark.service.spec.ts
> +    });
넵 확인하고 주석 처리 변경했습니다!

2024-03-14 14:54 UTC, Wanderer94 commented on src/bookmark/bookmark.service.spec.ts
> +      spyDeleteBookmarkFn.mockResolvedValueOnce(Promise.resolve({ affected: 1 }));
그런데 이 경우에는 delete를 하게 되는 과정이 북마크를 찾고 -> 해당하는 북마크를 삭제 이기 때문에 findOneby를 사용해서 찾았다고 가정하고 아래에서 영향을 받았는지 안받았는지로 delete되었음을 정상 확인했거든요

목처리를 안한다면 어떻게 해볼 수 있을까요?

2024-03-15 00:27 UTC, JeYeongR commented on src/bookmark/bookmark.service.spec.ts
> +      spyDeleteBookmarkFn.mockResolvedValueOnce(Promise.resolve({ affected: 1 }));
삭제 로직에서 findOneby도 사용하니 목처리 해주고, delete는 호출이 되는지 확인하면 좋을 거 같아요

2024-03-15 00:29 UTC, JeYeongR commented on src/bookmark/bookmark.service.ts
> +    await this.bookmarkRepository.delete(foundBookmark);
로직에 찾는 과정이 있으면 remove 하는 게 좋아 보입니다

2024-03-15 08:52 UTC, Wanderer94 commented on src/bookmark/bookmark.service.spec.ts
> +      spyDeleteBookmarkFn.mockResolvedValueOnce(Promise.resolve({ affected: 1 }));
넵 delete 호출되는 과정확인하는 순서를 하나 추가해두겠습니다

2024-03-15 08:52 UTC, Wanderer94 commented on src/bookmark/bookmark.service.ts
> +    await this.bookmarkRepository.delete(foundBookmark);
아 그러네요 remove가 이 경우에는 좀 더 적합 할 것 같습니다 수정할게요!

2024-03-15 15:07 UTC, JeYeongR approved these changes

2024-03-16 06:25 UTC, merged